### ISSUE TITLE
Add demo

### ISSUE THREAD

**Issue by sheepla** [sheepla/srss#10]
https://user-images.githubusercontent.com/62412884/170834853-97a373f0-98cf-47db-81fe-26e4b0f14ef2.mp4

**Comment by sheepla** [comment]
Hmm, this mp4 couldn't be added on README.md 🤨

**Comment by kllmanu** [comment]
@sheepla A screenshot would be nice though ❤️

**Comment by sheepla** [comment]
Thank you!

**Comment by sheepla** [comment]
Done

**Comment by sheepla** [comment]
![srss-demo](https://user-images.githubusercontent.com/62412884/184543394-b79df2de-e8ef-4812-a767-7b3a7d26e746.gif)

Update
