### ISSUE TITLE
A sponsor's entrance is required

### ISSUE THREAD

**Issue by linbuxiao** [sheepla/srss#28]
I'd like to buy you a cup of coffee.

Your code style makes me feel comfortable and inspired.

**Comment by sheepla** [comment]
Wow, I was very impressed!! 🥰 
I'm sorry, I have no plans to recruit sponsors yet but I'm proud of what you think of it. I'd like to thank you from the bottom of my heart. 💞

**Comment by linbuxiao** [comment]
> Wow, I was very impressed!! 🥰 I'm sorry, I have no plans to recruit sponsors yet but I'm proud of what you think of it. I'd like to thank you from the bottom of my heart. 💞

Please let us know if such an opportunity arises. Your creativity deserves more support. Thank you.
